### ISSUE TITLE
catkin package definitions miss some "DEPENDS" and "CATKIN_DEPENDS"

### ISSUE THREAD

**Issue by marc-hanheide** [OrebroUniversity/navigation_oru-release#11]
e.g. [here](https://github.com/OrebroUniversity/navigation_oru-release/blob/master/orunav_generic/CMakeLists.txt#L21):

```
catkin_package(
  INCLUDE_DIRS include
#  LIBRARIES orunav_generic
#  CATKIN_DEPENDS other_catkin_pkg
#  DEPENDS Eigen3 Boost
)
```

The `#` needs to be removed. Also applied in other packages, e.g. `orunav_rviz`. This should be checked for across the board.

**Comment by h72a65** [comment]
I did check through the repo and updated the DEPENDS and CATKIN_DEPENDS. I'll leave this open until we now it went through the 'release' process.
